### ISSUE TITLE
[Doc] Syntax for StringUtil#detectLineBreak

### ISSUE THREAD

**Issue by pyrech** [gnugat/redaktilo#112]
As the method `detectLineBreak` is static in the class `StringUtil`, shouldn't it be mentionned with the `::` symbol?

So if you agree, `StringUtil#detectLineBreak` should be replaced by `StringUtil::detectLineBreak` in `CHANGELOG.md` and `doc/03-reference.md`

**Comment by gnugat** [comment]
That's a tricky question... @WouterJ, what do you think? Should we keep `#` for every methods, or should we make an exception for static ones?

**Comment by WouterJ** [comment]
:+1: for using `::` for statics

**Comment by gnugat** [comment]
Then :+1: :)
